name: Build ModOrganizer 2

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

env:
  VCPKG_BINARY_SOURCES: ${{ vars.AZ_BLOB_VCPKG_URL != '' && format('clear;x-azblob,{0},{1},readwrite', vars.AZ_BLOB_VCPKG_URL, secrets.AZ_BLOB_SAS) || '' }}

jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Install Qt 6.11.1
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.11.1'
          arch: 'win64_msvc2022_64'
          modules: 'qtpositioning qtwebchannel qtwebengine qtwebsockets qtnetworkauth'
          py7zrversion: '==1.1.0'
          dir: 'D:/a/modorganizer'

      - name: Build ModOrganizer
        id: build-modorganizer
        uses: ModOrganizer2/build-with-mob-action@master
        with:
          qt-install: false
          mo2-dependencies: usvfs uibase bsatk esptk archive lootcli

      - name: Install ModOrganizer
        shell: pwsh
        run: |
          cmake --install vsbuild --config RelWithDebInfo
        working-directory: ./build/${{ github.event.repository.name }}

      - name: Package ModOrganizer
        uses: actions/upload-artifact@master
        with:
          name: modorganizer
          path: ./install/bin
